// src/schema/Certificate.ts

export const certificates = [
  {
    id: 1,
    title: "Problem Solving (Basic)",
    organization: "Hacker Rank",
    dateIssued: "Issued Apr 2024",
    certificateImage: "/problem.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/92c3018265f6",
  },
  {
    id: 2,
    title: "Design (Basic)",
    organization: "Skill Up",
    dateIssued: "Issued Aug 2025",
    certificateImage: "/canva.jpg",
    avatarImage: "/skill.jpg",
    certificateLink: "https://simpli-web.app.link/e/XmLMbgk0MVb",
  },
  {
    id: 3,
    title: "Node.js (Basic)",
    organization: "Hacker Rank",
    dateIssued: "Issued Apr 2024",
    certificateImage: "/hack-1.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/d9d32631d176",
  },
  {
    id: 4,
    title: "Frontend-Developer (Role)",
    organization: "Hacker Rank",
    dateIssued: "Issued Apr 2024",
    certificateImage: "/hack-2.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/0aa13c052071",
  },
  {
    id: 5,
    title: "SQL (Advanced)",
    organization: "Hacker Rank",
    dateIssued: "Issued Apr 2024",
    certificateImage: "/hack-3.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/d7f995124ac9",
  },
  {
    id: 6,
    title: "React (Basic)",
    organization: "Hacker Rank",
    dateIssued: "Issued May 2024",
    certificateImage: "/hack-4.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/d7f995124ac9",
  },
  {
    id: 7,
    title: "CSS (Basic)",
    organization: "Hacker Rank",
    dateIssued: "Issued May 2024",
    certificateImage: "/hack-7.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/9b63c589ee25",
  },
  {
    id: 8,
    title: "JavaScript (Intermediate) ",
    organization: "Hacker Rank",
    dateIssued: "Issued May 2024",
    certificateImage: "/hack-6.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/4eeecd99e4c7",
  },
  {
    id: 9,
    title: "JavaScript (Basic) ",
    organization: "Hacker Rank",
    dateIssued: "Issued May 2024",
    certificateImage: "/hack-5.jpg",
    avatarImage: "/hack.jpg",
    certificateLink: "https://www.hackerrank.com/certificates/05de7f0b3fcb",
  },
];
